// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FTN.Models;

public partial class StageEntrancePartNumbers
{
    public int Id { get; set; }

    public int StageEntranceId { get; set; }

    public string PartNumber { get; set; }

    public int Quantity { get; set; }

    public DateTime? CreateAt { get; set; }

    public virtual StageEntrances StageEntrance { get; set; }
}